### ISSUE TITLE
Certificate issue (TLS)

### ISSUE THREAD

**Issue by kmpeterson** [Tatsh/mb8611#171]
(Before I get to the issue, please indulge me: I'm not primarily a Python - or any sort of - developer, so apologies is this is obvious.  In the same vein, I worked on trying to reverse-engineer this functionality for two days before I found your package, so _many_ thanks for rescuing me from impending insanity.)

(I've had this unit for a few years but I'd been fighting with it and dropped dealing with it's issues - picking up now.)

Initial testing is really successful.  However, I'm getting stopped out of the gate by the TLS cert issue: I've added locally  `self.session.verify = False` in `client.py` to ignore the self-signed certificate, but although I've cured the initial complaint I'm uncertain if there's not a better approach to this - or why you hadn't run into it yourself?  

Again, _thanks_ for this.

**Comment by Tatsh** [comment]
I am willing to accept a PR for the issue. I cannot support this project as I do not use the modem anymore.

**Comment by kmpeterson** [comment]
Thanks!  However, I too am very close to not using this modem anymore either.  Appreciate the response, and thanks for your work.
