### ISSUE TITLE
Package not available on pip?

### ISSUE THREAD

**Issue by LibertyChief** [Tatsh/mb8611#58]
I was unable to find this package on the Python Package Index
I also cannot find a setup.py in the package

How does one install this?

**Comment by Tatsh** [comment]
Sorry it's not yet on there. The README is a template. The easiest way right now is to download an archive or use a Git URI with `pip`.

```shell
pip install git+https://github.com/Tatsh/mb8611-cli@master
```

I'll use this issue for tracking a release.

- [ ] Cruft update
- [ ] Tag
- [ ] Add tests
- [ ] Add docs
- [ ] Add man page
- [ ] Publish to PyPI

**Comment by Tatsh** [comment]
This is complete: https://pypi.org/project/mb8611/
